#ifndef VOYAH_VERSION_H
#define VOYAH_VERSION_H

#define VOYAH_VERSION_MAJOR 1
#define VOYAH_VERSION_MINOR 0
#define VOYAH_VERSION_PATCH 0

#define VOYAH_VERSION_STRING "1.0.0"
#define VOYAH_VERSION_FULL   "VoYah Scheduler " VOYAH_VERSION_STRING

#endif // VOYAH_VERSION_H
